####################################
# ! 服务配置
####################################
server:
  port: 8043
####################################
# ! 应用配置
####################################

mina:
  port: 5002
